#!/usr/bin/env python3
"""Generate a deterministic docs index from the repository's Markdown sources."""

from __future__ import annotations

import argparse
import os
from pathlib import Path


DEFAULT_OUTPUT = Path("docs/reference/GENERATED_DOCS_INDEX.md")
DOC_GROUPS = (
    ("Top-level docs", Path("docs"), False),
    ("Chapter docs", Path("docs/chapters"), True),
    ("Guides", Path("docs/guides"), True),
    ("Reference benchmarks", Path("docs/reference/benchmarks"), True),
    ("Reference models", Path("docs/reference/models"), True),
)


def _collect_markdown(source_root: Path, exclude: Path | None = None) -> list[Path]:
    if not source_root.exists():
        return []
    files = [
        path
        for path in source_root.rglob("*.md")
        if path.is_file() and (exclude is None or path.resolve() != exclude.resolve())
    ]
    return sorted(files, key=lambda p: p.relative_to(source_root).as_posix())


def _format_group(title: str, source_root: Path, files: list[Path], docs_root: Path) -> list[str]:
    lines = [f"## {title}", ""]
    if not files:
        lines.append("_No Markdown sources found._")
        lines.append("")
        return lines

    for path in files:
        rel = path.relative_to(docs_root)
        link = os.path.relpath(path, docs_root / "reference")
        if source_root == docs_root:
            link = os.path.relpath(path, docs_root / "reference")
        lines.append(f"- [{rel.as_posix()}]({link.replace(os.sep, '/')})")
    lines.append("")
    return lines


def build_index(root: Path, output: Path) -> str:
    docs_root = root / "docs"
    lines = [
        "# Generated Docs Index",
        "",
        "This file is generated by `scripts/docs/generate_docs_index.py`.",
        "",
    ]

    for title, relative_root, include_nested in DOC_GROUPS:
        source_root = root / relative_root
        exclude = output if source_root in output.parents or source_root == output.parent else None
        if include_nested:
            files = _collect_markdown(source_root, exclude=exclude)
        else:
            files = sorted(
                [
                    path
                    for path in source_root.glob("*.md")
                    if path.is_file() and (exclude is None or path.resolve() != exclude.resolve())
                ],
                key=lambda p: p.name,
            )
        lines.extend(_format_group(title, source_root, files, docs_root))

    return "\n".join(lines).rstrip() + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[2],
        help="Repository root to scan.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Generated markdown file to write or check.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the generated file is missing or stale.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = args.root.resolve()
    output = (root / args.output).resolve() if not args.output.is_absolute() else args.output.resolve()
    content = build_index(root, output)

    if args.check:
        try:
            existing = output.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"missing generated docs index: {output}")
            return 1
        if existing != content:
            print(f"stale generated docs index: {output}")
            return 1
        print(f"generated docs index is current: {output}")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"wrote generated docs index: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
