#!/bin/bash
set -euo pipefail

# Generated by n5_frontdoor_drafter_retest.sh.
# Run only in a coordinated clean window after the strict preflight is ready.

export LLAMA_CPP_DIR='/mnt/raid0/llm/llama.cpp-experimental'
export LLAMA_SERVER='/mnt/raid0/llm/llama.cpp-experimental/build-hip/bin/llama-server'
export LLAMA_LIB_DIR='/mnt/raid0/llm/llama.cpp-experimental/build-hip/bin'
export TARGET_MODEL='/mnt/raid0/llm/models/Qwen3.6-35B-A3B-MTP-Q8_0.gguf'
export DRAFT_MODEL='/mnt/raid0/llm/scratch/n5/Qwen3.5-0.8B-Q8_0.frontdoor-mtp-specials.gguf'
export PYTHON_BIN='/mnt/raid0/llm/epyc-inference-research/.venv/bin/python'
export OUTPUT_DIR='/mnt/raid0/llm/epyc-inference-research/data/specdec_frontdoor_alpha/n5_retest_v7_semantic_preflight_20260716T190817Z'
export PORT='19087'
export THREADS='96'
export CONTEXT='8192'
export UBATCH='8192'
export N_PREDICT='96'
export DRAFT_MAX='1'
export N_PROMPTS='8'
export MIN_DRAFT_RATIO='0.25'

'/mnt/raid0/llm/epyc-inference-research'/scripts/benchmark/n5_frontdoor_drafter_retest.sh --execute

# N5 external-draft server launch command used internally by --execute:
# env LD_LIBRARY_PATH=/mnt/raid0/llm/llama.cpp-experimental/build-hip/bin numactl --interleave=all /mnt/raid0/llm/llama.cpp-experimental/build-hip/bin/llama-server -m /mnt/raid0/llm/models/Qwen3.6-35B-A3B-MTP-Q8_0.gguf -t 96 -np 1 -c 8192 -ub 8192 -ngl 0 --port 19087 --metrics --slots --jinja --reasoning auto -fa on -ctk q8_0 -ctv q8_0 -md /mnt/raid0/llm/scratch/n5/Qwen3.5-0.8B-Q8_0.frontdoor-mtp-specials.gguf --spec-type draft-tree --spec-draft-n-max 1 --spec-draft-p-split 0.05 >'/mnt/raid0/llm/epyc-inference-research/data/specdec_frontdoor_alpha/n5_retest_v7_semantic_preflight_20260716T190817Z/llama-server.log' 2>&1
