#!/usr/bin/env bash
set -euo pipefail

# OP-2 operator quiet-window commands.
# This file is generated by op2_quiet_window_prep.py and is intentionally not
# executed by that helper. Run it only inside an approved quiet window.

export OP2_RUN_ROOT="${OP2_RUN_ROOT:-/mnt/raid0/llm/epyc-inference-research/docs/data/op2_quiet_window_prep_20260719}"
export FRONTDOOR_Q8="${FRONTDOOR_Q8:-/mnt/raid0/llm/models/Qwen3.6-35B-A3B-MTP-Q8_0.gguf}"
mkdir -p "$OP2_RUN_ROOT"/{approvals,preflight,attestations,live-v6,canonical-v6,b1-barrier-fusion,b4-dsa-d3,routing}

cd /mnt/raid0/llm/epyc-orchestrator
python scripts/server/preflight_gate.py \
  --require-servers \
  --output-dir "$OP2_RUN_ROOT/attestations" \
  --json | tee "$OP2_RUN_ROOT/preflight/live_stack_preflight.json"

cd /mnt/raid0/llm/epyc-inference-research
python3 scripts/benchmark/perf_counter_preflight.py \
  --probe \
  --strict \
  --output-json "$OP2_RUN_ROOT/preflight/perf_counter_preflight.json" \
  --output-md "$OP2_RUN_ROOT/preflight/perf_counter_preflight.md"

python3 scripts/benchmark/cpu_bench_clean_preflight.py \
  --output-json "$OP2_RUN_ROOT/preflight/cpu_clean_record_only.json" \
  --strict

cd /mnt/raid0/llm/epyc-orchestrator
python scripts/server/orchestrator_stack.py status \
  | tee "$OP2_RUN_ROOT/live-v6/orchestrator_stack_status.txt"

ps -eo pid,lstart,comm,args \
  | rg 'llama-server|uvicorn|autopilot|perf|rocprof' \
  > "$OP2_RUN_ROOT/live-v6/process_snapshot.txt" || true

for pid in $(pgrep -f '/mnt/raid0/llm/llama.cpp/build/bin/llama-server' || true); do
  mkdir -p "$OP2_RUN_ROOT/live-v6/pid-${pid}"
  ps -p "$pid" -o pid,lstart,etime,comm,args > "$OP2_RUN_ROOT/live-v6/pid-${pid}/ps.txt"
  tr '\0' '\n' < "/proc/${pid}/environ" \
    | rg '^(GGML_IQK|LD_LIBRARY_PATH|OMP_|KMP_)=' \
    > "$OP2_RUN_ROOT/live-v6/pid-${pid}/environ.filtered.txt" || true
  rg -a 'llama.cpp/build|libllama|libggml' "/proc/${pid}/maps" \
    > "$OP2_RUN_ROOT/live-v6/pid-${pid}/maps.llama.txt" || true
done

cat > "$OP2_RUN_ROOT/live-v6/README.role_smokes.md" <<'EOF'
# Live v6 role smokes

For each hot role/port from orchestrator_stack status, run one fixed request and
record role, port, pid, request JSON, response JSON, exact OP2_READY pass/fail,
latency, usage/timing fields, and output hash.

Example request body:
{"model":"local","messages":[{"role":"user","content":"Return exactly: OP2_READY"}],"temperature":0,"seed":42,"max_tokens":32}
EOF

cd /mnt/raid0/llm/epyc-inference-research
python3 scripts/benchmark/cpu_bench_clean_preflight.py \
  --run-sentinel \
  --output-json "$OP2_RUN_ROOT/canonical-v6/cpu_clean_sentinel.json" \
  --strict

./scripts/benchmark/bench_canonical.sh \
  -m "$FRONTDOOR_Q8" \
  -p 0 \
  -n 128 \
  -r 10 \
  --dry-run \
  -- -o json \
  > "$OP2_RUN_ROOT/canonical-v6/frontdoor_q8_tg128.dryrun.txt" 2>&1

./scripts/benchmark/bench_canonical.sh \
  -m "$FRONTDOOR_Q8" \
  -p 0 \
  -n 128 \
  -r 10 \
  -- -o json \
  > "$OP2_RUN_ROOT/canonical-v6/frontdoor_q8_tg128.results.json" \
  2> "$OP2_RUN_ROOT/canonical-v6/frontdoor_q8_tg128.stderr.txt"

cat > "$OP2_RUN_ROOT/b1-barrier-fusion/status.json" <<'EOF'
{"stage":"b1_barrier_fusion_ab","status":"skipped_not_staged","reason":"no current v7 barrier-fusion flag or immutable binary pair"}
EOF

cat > "$OP2_RUN_ROOT/b4-dsa-d3/status.json" <<'EOF'
{"stage":"b4_dsa_d3_profile","status":"closed_no_go","reason":"D3.1 profile found Lightning Indexer at only 1.08% of cycle samples"}
EOF
