#!/usr/bin/env python3
"""Generate a deterministic index over the repo's analysis-report artifacts."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
from typing import Callable


DEFAULT_OUTPUT = Path("docs/reference/ANALYSIS_REPORTS_INDEX.md")
REPORT_TOKENS = ("analysis", "report", "summary")


def _has_reportish_name(path: Path) -> bool:
    name = path.name.lower()
    return any(token in name for token in REPORT_TOKENS)


def _is_template(path: Path) -> bool:
    return "template" in path.name.lower()


def _has_hidden_path(path: Path) -> bool:
    return any(part.startswith(".") for part in path.parts)


def _is_research_note(path: Path) -> bool:
    return path.suffix == ".md" and not _is_template(path) and _has_reportish_name(path)


def _is_experiment_report(path: Path) -> bool:
    return path.suffix == ".md" and not _is_template(path)


def _is_reference_benchmark(path: Path) -> bool:
    return path.suffix == ".md" and not _is_template(path)


def _is_benchmark_result(path: Path) -> bool:
    return path.suffix in {".md", ".json"} and _has_reportish_name(path) and not _is_template(path)


def _is_data_report(path: Path) -> bool:
    return path.suffix in {".md", ".json"} and _has_reportish_name(path) and not _is_template(path) and not _has_hidden_path(path)


def _is_orchestration_report(path: Path) -> bool:
    return path.suffix == ".md" and _has_reportish_name(path) and not _is_template(path)


REPORT_GROUPS: tuple[tuple[str, Path, Callable[[Path], bool]], ...] = (
    ("Research notes", Path("research"), _is_research_note),
    ("Experiment analyses", Path("docs/experiments"), _is_experiment_report),
    ("Reference benchmark docs", Path("docs/reference/benchmarks"), _is_reference_benchmark),
    ("Benchmark run summaries", Path("benchmarks/results"), _is_benchmark_result),
    ("Research data summaries", Path("data"), _is_data_report),
    ("Orchestration reports", Path("orchestration"), _is_orchestration_report),
)


def _collect(source_root: Path, predicate: Callable[[Path], bool], output: Path) -> list[Path]:
    if not source_root.exists():
        return []

    exclude = output.resolve()
    files = [
        path
        for path in source_root.rglob("*")
        if path.is_file() and predicate(path) and path.resolve() != exclude
    ]
    return sorted(files, key=lambda path: path.relative_to(source_root).as_posix())


def _format_group(title: str, files: list[Path], docs_root: Path, root: Path) -> list[str]:
    lines = [f"## {title}", ""]
    if not files:
        lines.append("_No matching report sources found._")
        lines.append("")
        return lines

    for path in files:
        rel = path.relative_to(root)
        link = os.path.relpath(path, docs_root / "reference").replace(os.sep, "/")
        lines.append(f"- [{rel.as_posix()}]({link})")
    lines.append("")
    return lines


def build_index(root: Path, output: Path) -> str:
    docs_root = root / "docs"
    lines = [
        "# Generated Analysis Reports Index",
        "",
        "This file is generated by `scripts/analysis/generate_analysis_reports_index.py`.",
        "",
        "It indexes deterministic Markdown and JSON report artifacts that already exist in the repository.",
        "",
    ]

    for title, relative_root, predicate in REPORT_GROUPS:
        source_root = root / relative_root
        files = _collect(source_root, predicate, output)
        lines.extend(_format_group(title, files, docs_root, root))

    return "\n".join(lines).rstrip() + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[2],
        help="Repository root to scan.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Generated markdown file to write or check.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the generated file is missing or stale.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = args.root.resolve()
    output = (root / args.output).resolve() if not args.output.is_absolute() else args.output.resolve()
    content = build_index(root, output)

    if args.check:
        try:
            existing = output.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"missing generated analysis reports index: {output}")
            return 1
        if existing != content:
            print(f"stale generated analysis reports index: {output}")
            return 1
        print(f"generated analysis reports index is current: {output}")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"wrote generated analysis reports index: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
